# текущая директория для этого файла otester, а текущая директория для контейнера - директория / в системе linux.
# то есть внутри контейнера адрес директории uploads будет /app/uploads (app - это рабочая директорая, указанная в Dockerfile командой WORKDIR)
networks:
  net:
   
services:
  client:
    container_name: otester_client
    image: osscore/otester-client
    depends_on:
      - server
    ports:
      - 4200:80
    networks:
      - net
    volumes:
      - ./client/node_modules:/node_modules
   
  server:
    container_name: otester_server
    # местонахождение Dockerfile
    image: osscore/otester-server
    restart: always
    environment:
      - DB_NAME=otester
      - DB_USER=postgres
      - DB_PASSWORD=1234
      - DB_HOST=db
      - DB_PORT=5432
    command: bash -c "curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin && python manage.py migrate && python manage.py runserver 0.0.0.0:5000"
    ports:
      - 5000:5000
    networks:
      - net
    depends_on:
      - db
    volumes:
        - ./server/uploads:/app/uploads

  redis:
      container_name: otester_redis
      image: redis:7.0.7
      networks:
        - net 
  celery:
      container_name: otester_celery
      restart: always
      image: osscore/otester-server
      environment:
        - DB_NAME=otester
        - DB_USER=postgres
        - DB_PASSWORD=1234
        - DB_HOST=db
        - DB_PORT=5432
      command: bash -c "curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin && celery -A server.celery worker --loglevel=INFO --pool=solo" 
      networks:
        - net
      depends_on:
        - redis
        - server
      volumes:
        - ./server/uploads:/app/uploads
  db:
      container_name: otester_db
      image: postgres:15
      environment:
        - POSTGRES_PASSWORD=1234
        - POSTGRES_DB=otester
      networks:
        - net
      volumes:
        - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:

      
